version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
    environment:
      - PORT=3000
    expose:
      - "3000"

  auth-proxy:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    environment:
      BASIC_AUTH_USER: ${BASIC_AUTH_USER:-staging}
      BASIC_AUTH_PASS: ${BASIC_AUTH_PASS:-staging}
    ports:
      - "8080:80"
    depends_on:
      - frontend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
